### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by najachai** [L-HeliantHuS/DuckyGo#2]
你好 请问有没有联系方式 方便与你商讨

**Comment by L-HeliantHuS** [comment]
qq 1984441370





------------------ 原始邮件 ------------------
发件人: najachai <notifications@github.com&gt;
发送时间: 2020年3月23日 18:36
收件人: L-HeliantHuS/DuckyGo <DuckyGo@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[L-HeliantHuS/DuckyGo] 作者你好 (#2)





 
你好 请问有没有联系方式 方便与你商讨
